/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_hnust_serverproviderc_my_JNIDemo */

#ifndef _Included_com_hnust_serverproviderc_my_JNIDemo
#define _Included_com_hnust_serverproviderc_my_JNIDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hnust_serverproviderc_my_JNIDemo
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hnust_serverproviderc_my_JNIDemo_sayHello
  (JNIEnv *, jclass);

/*
 * Class:     com_hnust_serverproviderc_my_JNIDemo
 * Method:    Hello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hnust_serverproviderc_my_JNIDemo_Hello
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
